export type DemoEvent = {
  id: string;
  slug: string;
  title: string;
  description: string;
  rules: string;
  category: 'TECHNICAL' | 'CULTURAL' | 'SPORTS' | 'MANAGEMENT' | 'OTHER';
  status: 'PUBLISHED';
  startsAt: string;
  endsAt: string | null;
  venue: string;
  feeInPaise: number;
  price?: number;
  capacity: number | null;
  isFlagship: boolean;
  shortDescription: string;
  registrationStartsAt: string;
  registrationEndsAt: string;
  imageUrl: string | null;
  theme: string | null;
  department: { name: string; slug: string } | null;
};

export const departments = [
  { id: 'cse', name: 'Computer Science', slug: 'computer-science' },
  { id: 'ece', name: 'Electronics', slug: 'electronics' },
  { id: 'mech', name: 'Mechanical', slug: 'mechanical' },
  { id: 'civil', name: 'Civil', slug: 'civil' },
  { id: 'mba', name: 'Management', slug: 'management' },
  { id: 'arts', name: 'Arts & Media', slug: 'arts-media' },
  { id: 'sports', name: 'Sports', slug: 'sports' },
  { id: 'general', name: 'General', slug: 'general' },
];

const additionalEvents: DemoEvent[] = [
  {
    id: 'evt-121', slug: 'design-dash', title: 'Design Dash', description: 'Sketch, prototype, and present an original answer to a real campus challenge.', rules: 'Teams of 2-3\nBring your own laptop\nFinal presentation: 5 minutes', category: 'OTHER', status: 'PUBLISHED', startsAt: '2026-10-15T13:00:00.000Z', endsAt: '2026-10-15T16:00:00.000Z', venue: 'Creative Studio', feeInPaise: 0, capacity: 50, isFlagship: false, shortDescription: 'A fast creative sprint from first sketch to final pitch.', registrationStartsAt: '2026-09-20T00:00:00.000Z', registrationEndsAt: '2026-10-12T23:59:59.000Z', imageUrl: null, theme: 'Design', department: { name: 'Arts & Media', slug: 'arts-media' },
  },
  {
    id: 'evt-122', slug: 'circuit-crafters', title: 'Circuit Crafters', description: 'Build a working circuit and solve a hands-on electronics challenge with your team.', rules: 'Teams of 2\nComponents provided\nSafety briefing required', category: 'TECHNICAL', status: 'PUBLISHED', startsAt: '2026-10-16T09:30:00.000Z', endsAt: '2026-10-16T12:30:00.000Z', venue: 'Electronics Lab 1', feeInPaise: 0, capacity: 48, isFlagship: false, shortDescription: 'Hands-on circuits, clever fixes, and a race to make it work.', registrationStartsAt: '2026-09-20T00:00:00.000Z', registrationEndsAt: '2026-10-13T23:59:59.000Z', imageUrl: null, theme: 'Electronics', department: { name: 'Electronics', slug: 'electronics' },
  },
  {
    id: 'evt-123', slug: 'theatre-in-the-round', title: 'Theatre in the Round', description: 'Student actors bring original scenes and familiar stories to an intimate open-air stage.', rules: 'Acts up to 12 minutes\nProps must be self-managed\nArrive for sound check', category: 'CULTURAL', status: 'PUBLISHED', startsAt: '2026-10-17T18:00:00.000Z', endsAt: '2026-10-17T21:00:00.000Z', venue: 'Garden Amphitheatre', feeInPaise: 0, capacity: 110, isFlagship: false, shortDescription: 'Original scenes and bright performances under the evening sky.', registrationStartsAt: '2026-09-21T00:00:00.000Z', registrationEndsAt: '2026-10-14T23:59:59.000Z', imageUrl: null, theme: 'Theatre', department: { name: 'Arts & Media', slug: 'arts-media' },
  },
  {
    id: 'evt-124', slug: 'basketball-3x3', title: 'Basketball 3x3', description: 'Fast half-court games, quick substitutions, and a campus bracket that comes down to the final shot.', rules: 'Teams of 3 plus one substitute\nStandard campus rules apply\nCheck in 20 minutes before play', category: 'SPORTS', status: 'PUBLISHED', startsAt: '2026-10-18T08:00:00.000Z', endsAt: '2026-10-18T14:00:00.000Z', venue: 'Outdoor Courts', feeInPaise: 0, capacity: 64, isFlagship: false, shortDescription: 'Three on three. One court. Bragging rights on the line.', registrationStartsAt: '2026-09-21T00:00:00.000Z', registrationEndsAt: '2026-10-15T23:59:59.000Z', imageUrl: null, theme: 'Basketball', department: { name: 'Sports', slug: 'sports' },
  },
  {
    id: 'evt-125', slug: 'market-makers', title: 'Market Makers', description: 'A lively pop-up marketplace where student teams test a product idea with real festival-goers.', rules: 'Teams of 2-5\nBring a low-waste product or concept\nSetup begins at 8:00 AM', category: 'MANAGEMENT', status: 'PUBLISHED', startsAt: '2026-10-19T10:00:00.000Z', endsAt: '2026-10-19T16:00:00.000Z', venue: 'Festival Walkway', feeInPaise: 0, capacity: 45, isFlagship: false, shortDescription: 'Put your idea out there and meet your first customers.', registrationStartsAt: '2026-09-22T00:00:00.000Z', registrationEndsAt: '2026-10-16T23:59:59.000Z', imageUrl: null, theme: 'Entrepreneurship', department: { name: 'Management', slug: 'management' },
  },
  {
    id: 'evt-126', slug: 'short-film-showcase', title: 'Short Film Showcase', description: 'Screen original short films and meet the student creators behind each story.', rules: 'Films up to 12 minutes\nSubmit MP4 in advance\nInclude credits and music permissions', category: 'CULTURAL', status: 'PUBLISHED', startsAt: '2026-10-20T18:30:00.000Z', endsAt: '2026-10-20T21:30:00.000Z', venue: 'Media Theatre', feeInPaise: 0, capacity: 95, isFlagship: false, shortDescription: 'Big-screen stories, made right here on campus.', registrationStartsAt: '2026-09-23T00:00:00.000Z', registrationEndsAt: '2026-10-17T23:59:59.000Z', imageUrl: null, theme: 'Film', department: { name: 'Arts & Media', slug: 'arts-media' },
  },
  {
    id: 'evt-127', slug: 'green-campus-build', title: 'Green Campus Build', description: 'Teams design a practical, measurable idea for a greener and more welcoming campus.', rules: 'Interdisciplinary teams encouraged\nIdeas should be implementable\nBring a one-page concept', category: 'OTHER', status: 'PUBLISHED', startsAt: '2026-10-22T10:00:00.000Z', endsAt: '2026-10-22T13:00:00.000Z', venue: 'Civil Design Lab', feeInPaise: 0, capacity: 60, isFlagship: false, shortDescription: 'Make one small campus change with a big ripple effect.', registrationStartsAt: '2026-09-24T00:00:00.000Z', registrationEndsAt: '2026-10-19T23:59:59.000Z', imageUrl: null, theme: 'Sustainability', department: { name: 'Civil', slug: 'civil' },
  },
  {
    id: 'evt-128', slug: 'open-mic-under-stars', title: 'Open Mic Under the Stars', description: 'Bring a poem, a song, a story, or just your best cheer for a welcoming open-mic night.', rules: 'Five minutes per performer\nSign up on arrival\nAll-ages, original work welcome', category: 'CULTURAL', status: 'PUBLISHED', startsAt: '2026-10-24T19:00:00.000Z', endsAt: '2026-10-24T22:00:00.000Z', venue: 'Library Lawn', feeInPaise: 0, capacity: 120, isFlagship: false, shortDescription: 'A microphone, an open sky, and a spot for your voice.', registrationStartsAt: '2026-09-24T00:00:00.000Z', registrationEndsAt: '2026-10-21T23:59:59.000Z', imageUrl: null, theme: 'Open Mic', department: { name: 'Arts & Media', slug: 'arts-media' },
  },
  {
    id: 'evt-129', slug: 'precision-pitstop', title: 'Precision Pitstop', description: 'A mechanical design and assembly challenge where speed matters only when the build is right.', rules: 'Teams of 3\nTools and parts provided\nSafety gear must be worn', category: 'TECHNICAL', status: 'PUBLISHED', startsAt: '2026-10-26T09:00:00.000Z', endsAt: '2026-10-26T12:00:00.000Z', venue: 'Mechanical Workshop', feeInPaise: 0, capacity: 40, isFlagship: false, shortDescription: 'Design, assemble, and test your way to a clean finish.', registrationStartsAt: '2026-09-25T00:00:00.000Z', registrationEndsAt: '2026-10-22T23:59:59.000Z', imageUrl: null, theme: 'Engineering', department: { name: 'Mechanical', slug: 'mechanical' },
  },
  {
    id: 'evt-130', slug: 'final-whistle-cup', title: 'Final Whistle Cup', description: 'A friendly multi-sport finale that brings campus teams together for one last festival showdown.', rules: 'Team entries welcome\nEvents announced at opening\nBring campus ID and sportswear', category: 'SPORTS', status: 'PUBLISHED', startsAt: '2026-10-30T13:00:00.000Z', endsAt: '2026-10-30T17:00:00.000Z', venue: 'Central Sports Ground', feeInPaise: 0, capacity: 150, isFlagship: false, shortDescription: 'One last team challenge before the festival curtain falls.', registrationStartsAt: '2026-09-25T00:00:00.000Z', registrationEndsAt: '2026-10-27T23:59:59.000Z', imageUrl: null, theme: 'Campus Cup', department: { name: 'Sports', slug: 'sports' },
  },
];

export const eventCategories = ['TECHNICAL', 'CULTURAL', 'SPORTS', 'MANAGEMENT', 'OTHER'] as const;

export const demoEvents: DemoEvent[] = [
  {
    id: 'evt-101',
    slug: 'codesprint-2026',
    title: 'CodeSprint 2026',
    description: 'An all-night engineering sprint where teams build, test, and pitch transformative solutions under real-world constraints.',
    rules: 'Teams of 3-5\nBring a laptop and charger\nUse only approved open-source libraries\nFinal round demo at 9:00 PM',
    category: 'TECHNICAL',
    status: 'PUBLISHED',
    startsAt: '2026-10-18T10:00:00.000Z',
    endsAt: '2026-10-18T19:30:00.000Z',
    venue: 'Innovation Hall, Main Campus',
    feeInPaise: 0,
    capacity: 120,
    isFlagship: true,
    shortDescription: 'Build the future with a 12-hour innovation challenge.',
    registrationStartsAt: '2026-09-01T00:00:00.000Z',
    registrationEndsAt: '2026-10-12T23:59:59.000Z',
    imageUrl: null,
    theme: 'Flagship',
    department: { name: 'Computer Science', slug: 'computer-science' },
  },
  {
    id: 'evt-102',
    slug: 'nebula-nights',
    title: 'Nebula Nights',
    description: 'A live music, dance, and cultural showcase celebrating the creative spirit of the campus through performance, color, and rhythm.',
    rules: 'Performances curated by faculty and student coordinators\nNo late entries after 7:15 PM\nFollow stage instructions',
    category: 'CULTURAL',
    status: 'PUBLISHED',
    startsAt: '2026-10-19T18:30:00.000Z',
    endsAt: '2026-10-19T22:30:00.000Z',
    venue: 'Open Air Amphitheatre',
    feeInPaise: 0,
    capacity: 400,
    isFlagship: true,
    shortDescription: 'Live music, dance, and vibrant performances under the night sky.',
    registrationStartsAt: '2026-09-05T00:00:00.000Z',
    registrationEndsAt: '2026-10-15T23:59:59.000Z',
    imageUrl: null,
    theme: 'Cultural',
    department: { name: 'Arts & Media', slug: 'arts-media' },
  },
  {
    id: 'evt-103',
    slug: 'robowar-arena',
    title: 'RoboWar Arena',
    description: 'Watch student-built robots battle in a designed arena while teams demonstrate engineering precision and strategy.',
    rules: 'Arena safety briefing mandatory\nOnly approved robots allowed\nNo external battery swaps',
    category: 'TECHNICAL',
    status: 'PUBLISHED',
    startsAt: '2026-10-16T12:00:00.000Z',
    endsAt: '2026-10-16T17:00:00.000Z',
    venue: 'Robotics Lab Arena',
    feeInPaise: 0,
    capacity: 150,
    isFlagship: true,
    shortDescription: 'Student robotics battle arena with engineering showcase.',
    registrationStartsAt: '2026-09-02T00:00:00.000Z',
    registrationEndsAt: '2026-10-10T23:59:59.000Z',
    imageUrl: null,
    theme: 'Robotics',
    department: { name: 'Electronics', slug: 'electronics' },
  },
  {
    id: 'evt-104',
    slug: 'bizbash',
    title: 'BizBash',
    description: 'A strategy and startup pitch challenge where students build business models, pitch to judges, and solve market problems.',
    rules: 'Pitch deck must be submitted 30 mins before session\nBusiness model must be original\nQ&A round with judges',
    category: 'MANAGEMENT',
    status: 'PUBLISHED',
    startsAt: '2026-10-17T14:00:00.000Z',
    endsAt: '2026-10-17T18:00:00.000Z',
    venue: 'Management Block',
    feeInPaise: 0,
    capacity: 90,
    isFlagship: true,
    shortDescription: 'Pitch, plan, and launch your next big idea.',
    registrationStartsAt: '2026-09-04T00:00:00.000Z',
    registrationEndsAt: '2026-10-11T23:59:59.000Z',
    imageUrl: null,
    theme: 'Business',
    department: { name: 'Management', slug: 'management' },
  },
  {
    id: 'evt-105',
    slug: 'campus-quiz-quest',
    title: 'Campus Quiz Quest',
    description: 'A high-energy quiz challenge spanning general knowledge, culture, technology, and fast recall rounds.',
    rules: 'Individual and team entries allowed\nRound 1 elimination format\nNo mobile devices during the quiz',
    category: 'TECHNICAL',
    status: 'PUBLISHED',
    startsAt: '2026-10-15T11:00:00.000Z',
    endsAt: '2026-10-15T13:30:00.000Z',
    venue: 'Seminar Hall A',
    feeInPaise: 0,
    capacity: 80,
    isFlagship: false,
    shortDescription: 'Fast-fire rounds on campus culture, tech, and current affairs.',
    registrationStartsAt: '2026-09-06T00:00:00.000Z',
    registrationEndsAt: '2026-10-09T23:59:59.000Z',
    imageUrl: null,
    theme: null,
    department: { name: 'General', slug: 'general' },
  },
  {
    id: 'evt-106',
    slug: 'pixel-praxis',
    title: 'Pixel Praxis',
    description: 'A design-focused challenge for creative minds to craft concepts, visual stories, and digital mockups under time pressure.',
    rules: 'Use design tools of choice\nSubmit before final evaluation\nCreative originality required',
    category: 'OTHER',
    status: 'PUBLISHED',
    startsAt: '2026-10-14T15:00:00.000Z',
    endsAt: '2026-10-14T18:00:00.000Z',
    venue: 'Media Studio',
    feeInPaise: 0,
    capacity: 60,
    isFlagship: false,
    shortDescription: 'Concept design sprint for creators and storytellers.',
    registrationStartsAt: '2026-09-08T00:00:00.000Z',
    registrationEndsAt: '2026-10-08T23:59:59.000Z',
    imageUrl: null,
    theme: 'Design',
    department: { name: 'Arts & Media', slug: 'arts-media' },
  },
  {
    id: 'evt-107',
    slug: 'paper-presentation-lab',
    title: 'Paper Presentation Lab',
    description: 'Students present research work, case studies, and emerging ideas on technology and social innovation to a panel of experts.',
    rules: 'Abstract submission required\nPresentation time limit 8 minutes\nDecks must be PDF format',
    category: 'TECHNICAL',
    status: 'PUBLISHED',
    startsAt: '2026-10-20T10:30:00.000Z',
    endsAt: '2026-10-20T13:30:00.000Z',
    venue: 'Research Forum Hall',
    feeInPaise: 0,
    capacity: 80,
    isFlagship: false,
    shortDescription: 'Share your ideas with faculty and student reviewers.',
    registrationStartsAt: '2026-09-03T00:00:00.000Z',
    registrationEndsAt: '2026-10-18T23:59:59.000Z',
    imageUrl: null,
    theme: 'Research',
    department: { name: 'Computer Science', slug: 'computer-science' },
  },
  {
    id: 'evt-108',
    slug: 'street-football-showdown',
    title: 'Street Football Showdown',
    description: 'A lively football tournament for campus teams with fast matches, cheers, and a competitive knockout format.',
    rules: 'Teams of 5\nNo metal studs\nMatch schedule announced on the day',
    category: 'SPORTS',
    status: 'PUBLISHED',
    startsAt: '2026-10-21T08:30:00.000Z',
    endsAt: '2026-10-21T16:00:00.000Z',
    venue: 'Sports Arena Turf',
    feeInPaise: 0,
    capacity: 100,
    isFlagship: false,
    shortDescription: 'Campus football tournament with fast-paced action.',
    registrationStartsAt: '2026-09-09T00:00:00.000Z',
    registrationEndsAt: '2026-10-18T23:59:59.000Z',
    imageUrl: null,
    theme: null,
    department: { name: 'Sports', slug: 'sports' },
  },
  {
    id: 'evt-109',
    slug: 'dance-spotlight',
    title: 'Dance Spotlight',
    description: 'A choreographed dance battle jam featuring competing teams and an audience-voted finale.',
    rules: 'Minimum 3 members\nOriginal choreography preferred\nMusic track to be submitted before stage rehearsal',
    category: 'CULTURAL',
    status: 'PUBLISHED',
    startsAt: '2026-10-22T17:30:00.000Z',
    endsAt: '2026-10-22T21:00:00.000Z',
    venue: 'Main Stage',
    feeInPaise: 0,
    capacity: 180,
    isFlagship: false,
    shortDescription: 'Compete with confidence and choreography.',
    registrationStartsAt: '2026-09-10T00:00:00.000Z',
    registrationEndsAt: '2026-10-17T23:59:59.000Z',
    imageUrl: null,
    theme: 'Dance',
    department: { name: 'Arts & Media', slug: 'arts-media' },
  },
  {
    id: 'evt-110',
    slug: 'startup-bootcamp',
    title: 'Startup Bootcamp',
    description: 'A mentorship-packed startup challenge where teams move from idea to value proposition to investor-ready pitch.',
    rules: '2-4 members per team\nMust explain traction or feasibility approach\nJudging based on clarity and execution',
    category: 'MANAGEMENT',
    status: 'PUBLISHED',
    startsAt: '2026-10-23T09:30:00.000Z',
    endsAt: '2026-10-23T13:00:00.000Z',
    venue: 'Startup Studio',
    feeInPaise: 0,
    capacity: 75,
    isFlagship: false,
    shortDescription: 'Turn a spark into a viable startup narrative.',
    registrationStartsAt: '2026-09-07T00:00:00.000Z',
    registrationEndsAt: '2026-10-19T23:59:59.000Z',
    imageUrl: null,
    theme: 'Startup',
    department: { name: 'Management', slug: 'management' },
  },
  {
    id: 'evt-111',
    slug: 'brainwave-sprint',
    title: 'Brainwave Sprint',
    description: 'A rapid-fire competitive coding challenge focused on algorithm design, speed, and real-world thinking.',
    rules: 'Individual event\nUse provided compilers only\nNo network access during the challenge',
    category: 'TECHNICAL',
    status: 'PUBLISHED',
    startsAt: '2026-10-24T11:00:00.000Z',
    endsAt: '2026-10-24T14:00:00.000Z',
    venue: 'Coding Lab 2',
    feeInPaise: 0,
    capacity: 60,
    isFlagship: false,
    shortDescription: 'Sharpen logic and watch the clock.',
    registrationStartsAt: '2026-09-11T00:00:00.000Z',
    registrationEndsAt: '2026-10-20T23:59:59.000Z',
    imageUrl: null,
    theme: 'Coding',
    department: { name: 'Computer Science', slug: 'computer-science' },
  },
  {
    id: 'evt-112',
    slug: 'voice-of-the-campus',
    title: 'Voice of the Campus',
    description: 'A singing and open-mic platform for confident performers with fresh lyrics and vocal energy.',
    rules: 'Solo or duo acts only\nBring instrument or backing track if required\nSound check at 5:00 PM',
    category: 'CULTURAL',
    status: 'PUBLISHED',
    startsAt: '2026-10-25T18:00:00.000Z',
    endsAt: '2026-10-25T21:30:00.000Z',
    venue: 'Performers Stage',
    feeInPaise: 0,
    capacity: 160,
    isFlagship: false,
    shortDescription: 'A vocal showcase for raw talent and stage presence.',
    registrationStartsAt: '2026-09-12T00:00:00.000Z',
    registrationEndsAt: '2026-10-21T23:59:59.000Z',
    imageUrl: null,
    theme: 'Music',
    department: { name: 'Arts & Media', slug: 'arts-media' },
  },
  {
    id: 'evt-113',
    slug: 'build-the-bot',
    title: 'Build the Bot',
    description: 'A hands-on robotics design event where students create functional autonomous bot prototypes from a theme challenge.',
    rules: 'Teams of 2-4\nUse provided kit\nFinal build must be demo-ready',
    category: 'TECHNICAL',
    status: 'PUBLISHED',
    startsAt: '2026-10-26T09:00:00.000Z',
    endsAt: '2026-10-26T15:00:00.000Z',
    venue: 'Prototype Lab',
    feeInPaise: 0,
    capacity: 90,
    isFlagship: false,
    shortDescription: 'Prototype, test, and refine your bot design.',
    registrationStartsAt: '2026-09-13T00:00:00.000Z',
    registrationEndsAt: '2026-10-22T23:59:59.000Z',
    imageUrl: null,
    theme: 'Robotics',
    department: { name: 'Electronics', slug: 'electronics' },
  },
  {
    id: 'evt-114',
    slug: 'frontier-fest',
    title: 'Frontier Fest',
    description: 'Explore student innovation through prototypes, tech demos, and cross-disciplinary displays designed to impress.',
    rules: 'Interdisciplinary teams welcome\nPoster and working demo required\nJudges reserve the right to shortlist',
    category: 'TECHNICAL',
    status: 'PUBLISHED',
    startsAt: '2026-10-27T10:00:00.000Z',
    endsAt: '2026-10-27T16:00:00.000Z',
    venue: 'Innovation Expo Hall',
    feeInPaise: 0,
    capacity: 140,
    isFlagship: false,
    shortDescription: 'A showcase of student-led prototypes and ideas.',
    registrationStartsAt: '2026-09-14T00:00:00.000Z',
    registrationEndsAt: '2026-10-23T23:59:59.000Z',
    imageUrl: null,
    theme: 'Innovation',
    department: { name: 'Mechanical', slug: 'mechanical' },
  },
  {
    id: 'evt-115',
    slug: 'cadence-cup',
    title: 'Cadence Cup',
    description: 'A high-energy rhythm competition celebrating movement, team coordination, and stage timing.',
    rules: 'Teams of 5-8\nPerformance under 4 minutes\nProps to be arranged by team',
    category: 'CULTURAL',
    status: 'PUBLISHED',
    startsAt: '2026-10-28T17:30:00.000Z',
    endsAt: '2026-10-28T20:30:00.000Z',
    venue: 'Courtyard Stage',
    feeInPaise: 0,
    capacity: 120,
    isFlagship: false,
    shortDescription: 'Mood, movement, and rhythm on a bright campus stage.',
    registrationStartsAt: '2026-09-15T00:00:00.000Z',
    registrationEndsAt: '2026-10-24T23:59:59.000Z',
    imageUrl: null,
    theme: 'Performance',
    department: { name: 'Arts & Media', slug: 'arts-media' },
  },
  {
    id: 'evt-116',
    slug: 'civils-bridge-battle',
    title: 'Bridge Battle',
    description: 'Student teams design and test mini bridge structures for strength, efficiency, and design thinking.',
    rules: 'Use specified materials\nBridge must pass load test\nDesign report required',
    category: 'TECHNICAL',
    status: 'PUBLISHED',
    startsAt: '2026-10-29T12:00:00.000Z',
    endsAt: '2026-10-29T15:00:00.000Z',
    venue: 'Civil Workshop',
    feeInPaise: 0,
    capacity: 70,
    isFlagship: false,
    shortDescription: 'Build structure, test limits, and optimize design.',
    registrationStartsAt: '2026-09-16T00:00:00.000Z',
    registrationEndsAt: '2026-10-25T23:59:59.000Z',
    imageUrl: null,
    theme: 'Civil',
    department: { name: 'Civil', slug: 'civil' },
  },
  {
    id: 'evt-117',
    slug: 'campus-marathon',
    title: 'Campus Marathon',
    description: 'A community-driven run bringing together runners, fitness enthusiasts, and cheer squads for a memorable campus morning.',
    rules: '5K and 10K categories\nParticipants should carry ID\nRegister before 7:00 AM on race day',
    category: 'SPORTS',
    status: 'PUBLISHED',
    startsAt: '2026-10-30T06:00:00.000Z',
    endsAt: '2026-10-30T10:00:00.000Z',
    venue: 'Main Avenue, Campus Garden',
    feeInPaise: 0,
    capacity: 200,
    isFlagship: false,
    shortDescription: 'Run together, celebrate together.',
    registrationStartsAt: '2026-09-18T00:00:00.000Z',
    registrationEndsAt: '2026-10-26T23:59:59.000Z',
    imageUrl: null,
    theme: 'Fitness',
    department: { name: 'Sports', slug: 'sports' },
  },
  {
    id: 'evt-118',
    slug: 'case-crack',
    title: 'Case Crack',
    description: 'Analytical case-solving challenge for aspiring managers and business thinkers.',
    rules: 'Teams of 2\nCase brief released 30 mins before event\nFinal pitch judged on clarity and strategy',
    category: 'MANAGEMENT',
    status: 'PUBLISHED',
    startsAt: '2026-10-31T14:00:00.000Z',
    endsAt: '2026-10-31T17:30:00.000Z',
    venue: 'Business Lab',
    feeInPaise: 0,
    capacity: 65,
    isFlagship: false,
    shortDescription: 'Solve a problem, propose a solution, pitch it sharp.',
    registrationStartsAt: '2026-09-17T00:00:00.000Z',
    registrationEndsAt: '2026-10-27T23:59:59.000Z',
    imageUrl: null,
    theme: 'Strategy',
    department: { name: 'Management', slug: 'management' },
  },
  {
    id: 'evt-119',
    slug: 'microcontroller-ignite',
    title: 'Microcontroller Ignite',
    description: 'Teams explore embedded systems and circuit design through practical problem-solving tasks.',
    rules: 'Teams of 3\nUse only the assigned components\nFinal working submission required',
    category: 'TECHNICAL',
    status: 'PUBLISHED',
    startsAt: '2026-11-01T09:30:00.000Z',
    endsAt: '2026-11-01T13:00:00.000Z',
    venue: 'Embedded Systems Lab',
    feeInPaise: 0,
    capacity: 55,
    isFlagship: false,
    shortDescription: 'Design, wire, and power your next microcontroller proof.',
    registrationStartsAt: '2026-09-20T00:00:00.000Z',
    registrationEndsAt: '2026-10-28T23:59:59.000Z',
    imageUrl: null,
    theme: 'Embedded',
    department: { name: 'Electronics', slug: 'electronics' },
  },
  {
    id: 'evt-120',
    slug: 'urban-artist-block',
    title: 'Urban Artist Block',
    description: 'A creative street-art and poster design challenge where teams craft bold visual expressions on theme-driven walls.',
    rules: 'Only approved colors and materials\nPoster size must match the brief\nEntries judged on originality',
    category: 'OTHER',
    status: 'PUBLISHED',
    startsAt: '2026-11-02T13:00:00.000Z',
    endsAt: '2026-11-02T17:00:00.000Z',
    venue: 'Art Courtyard',
    feeInPaise: 0,
    capacity: 75,
    isFlagship: false,
    shortDescription: 'Create bold visual stories with color and contrast.',
    registrationStartsAt: '2026-09-22T00:00:00.000Z',
    registrationEndsAt: '2026-10-29T23:59:59.000Z',
    imageUrl: null,
    theme: 'Art',
    department: { name: 'Arts & Media', slug: 'arts-media' },
  },
];

demoEvents.push(...additionalEvents);

const eventPrices = [
  0, 149, 99, 199, 0, 49, 149, 99, 0, 249,
  49, 0, 99, 149, 0, 199, 0, 149, 49, 0,
  99, 49, 0, 149, 199, 99, 49, 0, 249, 0,
];

demoEvents.forEach((event, index) => {
  const price = eventPrices[index] ?? 0;
  event.price = price;
  event.feeInPaise = price * 100;
});

export function getEventPrice(event: Pick<DemoEvent, 'price' | 'feeInPaise'>): number {
  return event.price ?? event.feeInPaise / 100;
}

export const demoAnnouncements = [
  'Registration is open for flagship events and curated campus showcases.',
  'New workshops, music nights, and team competitions announced this week.',
  'Volunteer and coordinator signups are now live for the festival crew.',
  'Campus transport and event timing schedules have been released.',
  'Flagship workshops have limited capacity, so early registration is recommended.',
];

export const demoSponsors = [
  { name: 'Spark Labs', website: 'https://example.com', logoUrl: 'https://images.unsplash.com/...', tier: 'Platinum' },
  { name: 'CampusKart', website: 'https://example.com', logoUrl: 'https://images.unsplash.com/...', tier: 'Gold' },
  { name: 'Nexora', website: 'https://example.com', logoUrl: 'https://images.unsplash.com/...', tier: 'Gold' },
  { name: 'Pulse media', website: 'https://example.com', logoUrl: 'https://images.unsplash.com/...', tier: 'Silver' },
];

export const demoGallery = [
  { id: 'gallery-1', imageUrl: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1200&q=80', alt: 'Festival crowd', caption: 'Campus energy' },
  { id: 'gallery-2', imageUrl: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1200&q=80', alt: 'Stage lights', caption: 'Night stage' },
  { id: 'gallery-3', imageUrl: 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1200&q=80', alt: 'Performance crowd', caption: 'Crowd favorites' },
  { id: 'gallery-4', imageUrl: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=1200&q=80', alt: 'Students engaging', caption: 'Live interaction' },
];
